/* ============================================================
   Braccis - base de datos de prendas
   ------------------------------------------------------------
   GENERADO AUTOMATICAMENTE por herramientas/generar_catalogo.py
   a partir de los PDF de catalogo.

   Se puede editar a mano sin problema (por ejemplo para cargar
   precios o cambiar una descripcion), pero tene en cuenta que si
   volves a correr el script se pisa todo. Lo mas seguro es
   cargar los cambios en el script y regenerar.
   ============================================================ */

const CATEGORIAS = [
  { id: "remeras", nombre: "Remeras" },
  { id: "camisas", nombre: "Camisas" },
  { id: "blusas", nombre: "Blusas" },
  { id: "tejidos", nombre: "Tejidos" },
  { id: "jeans", nombre: "Jeans" }
];

const PRODUCTOS = [
  { id: "jeans-repro", nombre: "Jeans Chupín Repro", codigo: "27V4101", categoria: "jeans", precio: null, descripcion: "Jeans chupín de tiro medio, elastizado.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-repro.jpg", galeria: [], destacado: false },
  { id: "jeans-gain", nombre: "Jeans Gain Black Oxford", codigo: "A26I4087", categoria: "jeans", precio: null, descripcion: "Jeans oxford semielastizado.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-gain.jpg", galeria: [], destacado: false },
  { id: "jeans-cird", nombre: "Jeans Oxford Cird", codigo: "27V4105", categoria: "jeans", precio: null, descripcion: "Jeans oxford de tiro medio, elastizado.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-cird.jpg", galeria: [], destacado: false },
  { id: "jeans-tampa", nombre: "Jeans Tampa Recto", codigo: "A26I4034", categoria: "jeans", precio: null, descripcion: "Jeans recto de tiro medio, elastizado.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-tampa.jpg", galeria: [], destacado: false },
  { id: "jeans-kady", nombre: "Jeans Recto Kady", codigo: "27V4106", categoria: "jeans", precio: null, descripcion: "Jeans recto de tiro medio, elastizado.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-kady.jpg", galeria: [], destacado: false },
  { id: "jeans-black-moon", nombre: "Jeans Black Moon Chupín", codigo: "A26I4086", categoria: "jeans", precio: null, descripcion: "Jeans chupín elastizado.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-black-moon.jpg", galeria: [], destacado: false },
  { id: "jeans-sunny", nombre: "Jeans Sunny", codigo: "27V4103", categoria: "jeans", precio: null, descripcion: "Jeans wide leg de tiro medio con apliques frontales.", tela: "", talles: ["24", "28", "30", "32", "34"], colores: [], foto: "img/prendas/jeans-sunny.jpg", galeria: ["img/prendas/jeans-sunny-2.jpg"], destacado: false },
  { id: "jeans-glam", nombre: "Jeans Recto Glam", codigo: "27V4104", categoria: "jeans", precio: null, descripcion: "Jeans recto elastizado, tiro medio con apliques laterales.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-glam.jpg", galeria: [], destacado: false },
  { id: "jeans-black-night", nombre: "Jeans Recto Black Night", codigo: "27V4102", categoria: "jeans", precio: null, descripcion: "Jeans recto elastizado, tiro medio con apliques frontales.", tela: "", talles: ["26", "28", "30", "32", "34", "36"], colores: [], foto: "img/prendas/jeans-black-night.jpg", galeria: ["img/prendas/jeans-black-night-2.jpg"], destacado: false },
  { id: "jeans-seiano", nombre: "Jeans Wide Leg Seiano", codigo: "A26I4078", categoria: "jeans", precio: null, descripcion: "Jeans wide leg de tiro medio, elastizado.", tela: "", talles: ["24", "26", "28", "30", "32", "34"], colores: [], foto: "img/prendas/jeans-seiano.jpg", galeria: ["img/prendas/jeans-seiano-2.jpg"], destacado: true },
  { id: "sunflower", nombre: "Remera Sunflower", codigo: "27V2210", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/sunflower-blanco.png" }, { nombre: "Negro", muestra: "img/colores/sunflower-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/sunflower-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/sunflower-gris.png" }, { nombre: "Verde", muestra: "img/colores/sunflower-verde.png" }], foto: "img/prendas/sunflower.jpg", galeria: ["img/prendas/sunflower-2.jpg"], destacado: true },
  { id: "roking", nombre: "Remera Roking", codigo: "27V2209", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/roking-blanco.png" }, { nombre: "Negro", muestra: "img/colores/roking-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/roking-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/roking-gris.png" }, { nombre: "Verde", muestra: "img/colores/roking-verde.png" }], foto: "img/prendas/roking.jpg", galeria: ["img/prendas/roking-2.jpg"], destacado: false },
  { id: "libel", nombre: "Remera Libel", codigo: "27V2208", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/libel-blanco.png" }, { nombre: "Negro", muestra: "img/colores/libel-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/libel-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/libel-gris.png" }, { nombre: "Verde", muestra: "img/colores/libel-verde.png" }], foto: "img/prendas/libel.jpg", galeria: ["img/prendas/libel-2.jpg"], destacado: false },
  { id: "infinity", nombre: "Remera Infinity", codigo: "27V2207", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello V con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/infinity-blanco.png" }, { nombre: "Negro", muestra: "img/colores/infinity-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/infinity-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/infinity-gris.png" }, { nombre: "Verde", muestra: "img/colores/infinity-verde.png" }], foto: "img/prendas/infinity.jpg", galeria: ["img/prendas/infinity-2.jpg"], destacado: false },
  { id: "hummers", nombre: "Remera Hummers", codigo: "27V2206", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello V con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/hummers-blanco.png" }, { nombre: "Negro", muestra: "img/colores/hummers-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/hummers-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/hummers-gris.png" }, { nombre: "Verde", muestra: "img/colores/hummers-verde.png" }], foto: "img/prendas/hummers.jpg", galeria: ["img/prendas/hummers-2.jpg"], destacado: false },
  { id: "somos", nombre: "Remera Somos", codigo: "27V2205", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/somos-blanco.png" }, { nombre: "Negro", muestra: "img/colores/somos-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/somos-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/somos-gris.png" }, { nombre: "Verde", muestra: "img/colores/somos-verde.png" }], foto: "img/prendas/somos.jpg", galeria: ["img/prendas/somos-2.jpg"], destacado: false },
  { id: "vive", nombre: "Remera Vive", codigo: "27V2204", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/vive-blanco.png" }, { nombre: "Negro", muestra: "img/colores/vive-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/vive-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/vive-gris.png" }, { nombre: "Verde", muestra: "img/colores/vive-verde.png" }], foto: "img/prendas/vive.jpg", galeria: ["img/prendas/vive-2.jpg"], destacado: false },
  { id: "cat-love", nombre: "Remera Cat Love", codigo: "27V2203", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/cat-love-blanco.png" }, { nombre: "Negro", muestra: "img/colores/cat-love-negro.png" }, { nombre: "Mostaza", muestra: "img/colores/cat-love-mostaza.png" }, { nombre: "Gris", muestra: "img/colores/cat-love-gris.png" }, { nombre: "Verde", muestra: "img/colores/cat-love-verde.png" }], foto: "img/prendas/cat-love.jpg", galeria: ["img/prendas/cat-love-2.jpg"], destacado: false },
  { id: "gio", nombre: "Polera Gio", codigo: "A26I2128", categoria: "remeras", precio: null, descripcion: "Polera de morley.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Arena", muestra: "img/colores/gio-arena.png" }, { nombre: "Verde", muestra: "img/colores/gio-verde.png" }, { nombre: "Negro", muestra: "img/colores/gio-negro.png" }, { nombre: "Crudo", muestra: "img/colores/gio-crudo.png" }], foto: "img/prendas/gio.jpg", galeria: ["img/prendas/gio-2.jpg", "img/prendas/gio-3.jpg", "img/prendas/gio-4.jpg"], destacado: true },
  { id: "moon-flower", nombre: "Remera Moon Flower", codigo: "A26I2141", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa y detalle de corte en los laterales.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/moon-flower-blanco.png" }, { nombre: "Camel", muestra: "img/colores/moon-flower-camel.png" }, { nombre: "Negro", muestra: "img/colores/moon-flower-negro.png" }], foto: "img/prendas/moon-flower.jpg", galeria: ["img/prendas/moon-flower-2.jpg"], destacado: false },
  { id: "moon", nombre: "Remera Moon", codigo: "A26I2143", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa y detalle de corte en los laterales.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/moon-blanco.png" }, { nombre: "Azul", muestra: "img/colores/moon-azul.png" }, { nombre: "Negro", muestra: "img/colores/moon-negro.png" }], foto: "img/prendas/moon.jpg", galeria: ["img/prendas/moon-2.jpg"], destacado: false },
  { id: "trendy", nombre: "Remera Trendy", codigo: "A26I2161", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo básica.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Negro" }, { nombre: "Blanco", muestra: "img/colores/trendy-blanco.png" }], foto: "img/prendas/trendy.jpg", galeria: ["img/prendas/trendy-2.jpg"], destacado: false },
  { id: "victoria", nombre: "Remera Victoria", codigo: "A26I2000", categoria: "remeras", precio: null, descripcion: "Remera cuello V, 100% algodón.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Negro", muestra: "img/colores/victoria-negro.png" }, { nombre: "Blanco", muestra: "img/colores/victoria-blanco.png" }], foto: "img/prendas/victoria.jpg", galeria: ["img/prendas/victoria-2.jpg"], destacado: false },
  { id: "perfectly", nombre: "Remera Perfectly", codigo: "A26I2142", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa y detalle de corte en los laterales.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/perfectly-blanco.png" }, { nombre: "Gris", muestra: "img/colores/perfectly-gris.png" }, { nombre: "Chocolate", muestra: "img/colores/perfectly-chocolate.png" }], foto: "img/prendas/perfectly.jpg", galeria: ["img/prendas/perfectly-2.jpg"], destacado: false },
  { id: "karma", nombre: "Remera Karma", codigo: "A26I2153", categoria: "remeras", precio: null, descripcion: "Remera de jersey, cuello redondo con estampa al frente.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/karma-blanco.png" }, { nombre: "Negro", muestra: "img/colores/karma-negro.png" }], foto: "img/prendas/karma.jpg", galeria: ["img/prendas/karma-2.jpg"], destacado: false },
  { id: "be-you", nombre: "Remera Be You", codigo: "A26I2154", categoria: "remeras", precio: null, descripcion: "Remera de jersey, cuello redondo con estampa al frente.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Crudo", muestra: "img/colores/be-you-crudo.png" }, { nombre: "Negro" }], foto: "img/prendas/be-you.jpg", galeria: ["img/prendas/be-you-2.jpg"], destacado: false },
  { id: "lirium", nombre: "Remera Lirium", codigo: "A26I2168", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Negro", muestra: "img/colores/lirium-negro.png" }, { nombre: "Blanco", muestra: "img/colores/lirium-blanco.png" }, { nombre: "Verde", muestra: "img/colores/lirium-verde.png" }], foto: "img/prendas/lirium.jpg", galeria: ["img/prendas/lirium-2.jpg"], destacado: false },
  { id: "jaguar", nombre: "Remera Jaguar", codigo: "A26I2167", categoria: "remeras", precio: null, descripcion: "Remera de algodón, cuello redondo con estampa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Verde M", muestra: "img/colores/jaguar-verde-m.png" }, { nombre: "Blanco", muestra: "img/colores/jaguar-blanco.png" }, { nombre: "Mostaza", muestra: "img/colores/jaguar-mostaza.png" }], foto: "img/prendas/jaguar.jpg", galeria: ["img/prendas/jaguar-2.jpg", "img/prendas/jaguar-3.jpg"], destacado: false },
  { id: "idalia", nombre: "Remera Tejida Idalia", codigo: "27V00429", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Beige" }, { nombre: "Negro" }, { nombre: "Chocolate" }], foto: "img/prendas/idalia.jpg", galeria: ["img/prendas/idalia-2.jpg", "img/prendas/idalia-3.jpg"], destacado: true },
  { id: "sweater-esmeralda", nombre: "Sweater", codigo: "A26I183", categoria: "tejidos", precio: null, descripcion: "Sweater tejido de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Negro", muestra: "img/colores/sweater-esmeralda-negro.png" }, { nombre: "Crudo", muestra: "img/colores/sweater-esmeralda-crudo.png" }, { nombre: "Chocolate", muestra: "img/colores/sweater-esmeralda-chocolate.png" }, { nombre: "Esmeralda" }], foto: "img/prendas/sweater-esmeralda.jpg", galeria: ["img/prendas/sweater-esmeralda-2.jpg", "img/prendas/sweater-esmeralda-3.jpg"], destacado: false },
  { id: "cowl-neck", nombre: "Buzo Cowl Neck Rústico", codigo: "A26I6013", categoria: "tejidos", precio: null, descripcion: "Buzo rústico con cuello cowl neck.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Verde", muestra: "img/colores/cowl-neck-verde.png" }, { nombre: "Beige", muestra: "img/colores/cowl-neck-beige.png" }], foto: "img/prendas/cowl-neck.jpg", galeria: [], destacado: true },
  { id: "chery", nombre: "Remera Tejida Chery", codigo: "27V00420", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Beige" }, { nombre: "Negro" }, { nombre: "Camel" }], foto: "img/prendas/chery.jpg", galeria: ["img/prendas/chery-2.jpg", "img/prendas/chery-3.jpg"], destacado: false },
  { id: "celina", nombre: "Remera Tejida Celina", codigo: "27V00408", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Beige" }, { nombre: "Negro" }, { nombre: "Chocolate" }], foto: "img/prendas/celina.jpg", galeria: ["img/prendas/celina-2.jpg"], destacado: false },
  { id: "julieta", nombre: "Remera Julieta", codigo: "27V00408", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Beige" }, { nombre: "Negro" }], foto: "img/prendas/julieta.jpg", galeria: ["img/prendas/julieta-2.jpg"], destacado: false },
  { id: "calista", nombre: "Remera Tejida Calista", codigo: "27V00428", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Crudo" }, { nombre: "Beige" }, { nombre: "Negro" }], foto: "img/prendas/calista.jpg", galeria: ["img/prendas/calista-2.jpg", "img/prendas/calista-3.jpg"], destacado: false },
  { id: "africa", nombre: "Sweater África", codigo: "27V00177", categoria: "tejidos", precio: null, descripcion: "Sweater tejido de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Azul" }, { nombre: "Beige" }, { nombre: "Gris" }], foto: "img/prendas/africa.jpg", galeria: ["img/prendas/africa-2.jpg", "img/prendas/africa-3.jpg"], destacado: false },
  { id: "beca", nombre: "Musculosa Tejida Beca", codigo: "27V00393", categoria: "tejidos", precio: null, descripcion: "Musculosa tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Bordo" }, { nombre: "Beige" }, { nombre: "Negro" }, { nombre: "Chocolate" }, { nombre: "Blanco" }], foto: "img/prendas/beca.jpg", galeria: ["img/prendas/beca-2.jpg", "img/prendas/beca-3.jpg", "img/prendas/beca-4.jpg", "img/prendas/beca-5.jpg"], destacado: false },
  { id: "marion", nombre: "Remera Tejida Marion", codigo: "27V00392", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Crudo" }, { nombre: "Beige" }, { nombre: "Negro" }, { nombre: "Chocolate" }], foto: "img/prendas/marion.jpg", galeria: ["img/prendas/marion-2.jpg", "img/prendas/marion-3.jpg", "img/prendas/marion-4.jpg"], destacado: false },
  { id: "analia", nombre: "Remera Tejida Analía", codigo: "27V00391", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Crudo" }, { nombre: "Beige" }, { nombre: "Negro" }], foto: "img/prendas/analia.jpg", galeria: ["img/prendas/analia-2.jpg", "img/prendas/analia-3.jpg"], destacado: false },
  { id: "nicky", nombre: "Remera Tejida Nicky", codigo: "27V00432", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Chocolate" }, { nombre: "Celeste" }, { nombre: "Negro" }], foto: "img/prendas/nicky.jpg", galeria: ["img/prendas/nicky-2.jpg", "img/prendas/nicky-3.jpg"], destacado: false },
  { id: "cassie", nombre: "Remera Tejida Cassie", codigo: "27V00394", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Camel" }, { nombre: "Blanco" }, { nombre: "Negro" }], foto: "img/prendas/cassie.jpg", galeria: ["img/prendas/cassie-2.jpg", "img/prendas/cassie-3.jpg"], destacado: false },
  { id: "barbara", nombre: "Remera Tejida Bárbara", codigo: "27V00423", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Crudo" }, { nombre: "Negro" }, { nombre: "Camel" }], foto: "img/prendas/barbara.jpg", galeria: ["img/prendas/barbara-2.jpg", "img/prendas/barbara-3.jpg"], destacado: false },
  { id: "kaia", nombre: "Remera Tejida Kaia", codigo: "27V00395", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Beige" }, { nombre: "Chocolate" }, { nombre: "Gris" }, { nombre: "Negro" }], foto: "img/prendas/kaia.jpg", galeria: ["img/prendas/kaia-2.jpg"], destacado: false },
  { id: "chantal", nombre: "Remera Tejida Chantal", codigo: "27V00424", categoria: "tejidos", precio: null, descripcion: "Remera tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Blanco" }, { nombre: "Negro" }, { nombre: "Chocolate" }], foto: "img/prendas/chantal.jpg", galeria: ["img/prendas/chantal-2.jpg"], destacado: false },
  { id: "cruella", nombre: "Tejido Cruella", codigo: "27V00427", categoria: "tejidos", precio: null, descripcion: "Prenda tejida de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Beige" }, { nombre: "Negro" }, { nombre: "Gris" }], foto: "img/prendas/cruella.jpg", galeria: ["img/prendas/cruella-2.jpg"], destacado: false },
  { id: "lauren", nombre: "Chaleco Tejido Lauren", codigo: "27V00430", categoria: "tejidos", precio: null, descripcion: "Chaleco tejido de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Chocolate" }, { nombre: "Negro" }, { nombre: "Crudo" }], foto: "img/prendas/lauren.jpg", galeria: ["img/prendas/lauren-2.jpg", "img/prendas/lauren-3.jpg"], destacado: false },
  { id: "galit", nombre: "Vestido Galit", codigo: "27V0086", categoria: "tejidos", precio: null, descripcion: "Vestido tejido de talle único.", tela: "", talles: ["Único"], colores: [{ nombre: "Crudo" }, { nombre: "Negro" }, { nombre: "Chocolate" }], foto: "img/prendas/galit.jpg", galeria: ["img/prendas/galit-2.jpg"], destacado: true },
  { id: "era", nombre: "Remera Era", codigo: "A26I2123", categoria: "remeras", precio: null, descripcion: "Remera de foil, cuello redondo.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Negro", muestra: "img/colores/era-negro.png" }], foto: "img/prendas/era.jpg", galeria: ["img/prendas/era-2.jpg"], destacado: false },
  { id: "nidia", nombre: "Blusa Nidia", codigo: "27V00356", categoria: "blusas", precio: null, descripcion: "Blusa de cuello redondo.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Negro", muestra: "img/colores/nidia-negro.png" }], foto: "img/prendas/nidia.jpg", galeria: ["img/prendas/nidia-2.jpg"], destacado: false },
  { id: "ons", nombre: "Camisa Ons", codigo: "27V1022", categoria: "camisas", precio: null, descripcion: "Camisa de lino.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Pardo", muestra: "img/colores/ons-pardo.png" }, { nombre: "Crudo", muestra: "img/colores/ons-crudo.png" }, { nombre: "Beige", muestra: "img/colores/ons-beige.png" }], foto: "img/prendas/ons.jpg", galeria: ["img/prendas/ons-2.jpg", "img/prendas/ons-3.jpg"], destacado: true },
  { id: "plumety", nombre: "Blusa Plumety", codigo: "27V1020", categoria: "blusas", precio: null, descripcion: "Blusa de plumetí con manga japonesa.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco", muestra: "img/colores/plumety-blanco.png" }, { nombre: "Negro", muestra: "img/colores/plumety-negro.png" }], foto: "img/prendas/plumety.jpg", galeria: ["img/prendas/plumety-2.jpg"], destacado: true },
  { id: "dante", nombre: "Camisa Dante", codigo: "27V1021", categoria: "camisas", precio: null, descripcion: "Camisa de fibrana con apliques en cuello y puño.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco" }, { nombre: "Negro", muestra: "img/colores/dante-negro.png" }, { nombre: "Pardo", muestra: "img/colores/dante-pardo.png" }], foto: "img/prendas/dante.jpg", galeria: ["img/prendas/dante-2.jpg"], destacado: false },
  { id: "dall", nombre: "Camisa Dall", codigo: "27V1023", categoria: "camisas", precio: null, descripcion: "Camisa de fibrana.", tela: "", talles: ["S", "M", "L", "XL"], colores: [{ nombre: "Blanco" }, { nombre: "Negro", muestra: "img/colores/dall-negro.png" }, { nombre: "Pardo", muestra: "img/colores/dall-pardo.png" }], foto: "img/prendas/dall.jpg", galeria: ["img/prendas/dall-2.jpg"], destacado: false }
];
